repos:
-   repo: local
    hooks:
    -   id: ruff-format
        name: ruff format
        entry: uv run ruff format .
        language: system
        types: [python]
        stages: [pre-commit]
    -   id: ruff-check
        name: ruff check
        entry: uv run ruff check . --fix
        language: system
        types: [python]
        stages: [pre-commit]
    -   id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
        stages: [pre-commit]